### ISSUE TITLE
发布商品页面的ui问题和逻辑问题

### ISSUE THREAD

**Issue by wdcyxxycdw** [TokyoShisenGroup/UTokyoMeru_Front_RN#1]
现在上传照片的ui在用户上传照片后不能正确显示，需要调整样式

另外，现在在图片上传成功获取url之后，无法发送给后端添加商品，打log也没有用，现在能确认是程序进到了发送请求那一行里，但后端也没有接收到请求

tag修改。现在的tag不能输入多个tag作为字符串数组，需要加一个功能，参考小红书

**Comment by wdcyxxycdw** [comment]
in progress

**Comment by cliecy** [comment]
你奴役我们，妈的
